### ISSUE TITLE
Epic - Core WP Update - Build Patterns 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#120]
### Epic and sprint owner
@AmnestyAM 

Some background info here #https://github.com/amnestywebsite/internal/issues/594 

### Sprints allocated 
Number of sprints: one (This will take longer)

## Goals 
So the scope here extended a bit, we not only want patterns but also block templates.

Build 4 block templates 
Build patterns for templates

#### Block Templates - In brand plugin 
- [ ] Report - https://github.com/amnestywebsite/amnesty-wp-theme/issues/2932
- [ ] Perspective - https://github.com/amnestywebsite/amnesty-wp-theme/issues/2934 (no patterns RQD)
- [ ] Press Release Plus https://github.com/amnestywebsite/amnesty-wp-theme/issues/2933
- [ ] Issue or Project Page https://github.com/amnestywebsite/amnesty-wp-theme/issues/2935

#### Patterns - In Humanity theme 

- [ ] #171
- [ ] #172
- [ ] #173
- [ ] #174
- [ ] #175
- [ ] #176
- [ ] #177
- [ ] #178
- [ ] #179
- [ ] #180
- [ ] #181
- [ ] https://github.com/amnestywebsite/humanity-theme/issues/132 

#### Other 
- [ ] #182
- [x] #184
- [ ] #183
- [x] #185
- [ ] #186
- [ ] #201

**Comment by AmnestyAM** [comment]
should we also look to remove the old links with icons block so its no longer selectable?

**Comment by jaymcp** [comment]
@AmnestyAM I think that makes sense; I've created a PR to hide it from the inserter https://github.com/amnestywebsite/humanity-theme/pull/235
