### ISSUE TITLE
Epic - Core WP Update - Gallery + Details Block + Group Block Support 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#124]
## Goals 
- Re-introduce the Gallery and Details blocks
- Deprecate the Collapsable block

---

- [x] amnestywebsite/humanity-theme#225
- [x] amnestywebsite/wp-plugin-amnesty-branding#24
- [x] amnestywebsite/wp-plugin-amnesty-branding#25
- [x] amnestywebsite/humanity-theme#228
- [x] amnestywebsite/humanity-theme#229
- [x] amnestywebsite/wp-plugin-amnesty-branding#26
- [x] #231

---

### Sprints allocated 
Number of sprints: 1

**Comment by AmnestyAM** [comment]
https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/gallery-block-test/

Details block is cool, but any chance we can extend that to have this functionality
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/b593564b-ed97-4674-8e98-bd0488058ec4)

**Comment by jaymcp** [comment]
The Details block has the collapsed/open field (see screenshot), so I'll look into the anchor

![](http://bigbite.im/i/AuYQQw+)

**Comment by jaymcp** [comment]
PR created to enable the HTML anchor

**Comment by AmnestyAM** [comment]
thanks

**Comment by AmnestyAM** [comment]
https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/gallery-block-test/#anchor LGTM 



![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/66cb9f70-031a-4f96-a4bb-952e1c359246)



![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/fd4148bb-2281-43ef-a7b2-97495c7d538e)

@SophieAmnesty FYI the new core details block works a little differently
