### ISSUE TITLE
Epic - Swap old templates for FSE template

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#246]
### Sprints allocated 
Number of sprints: 1 (2+ for all of them but we will make a start)
Link to sprint if known: TBC

## Goals 
- start swapping old templates for FSE template
- This will allow us to build FSE "templates" for the really big patterns such as Issue pages, that were too big for patterns but built as patterns anyway. 

## Tickets
- [x] #369
- [x] #380
- [x] #361
- [x] #362
- [x] #346
- [x] #376
- [x] #370
- [x] #373
- [x] #385
- [x] #372
- [x] #345

## Think about (optional)
- Tickets for translations
- Tickets for content

- home page
- archive template
- single post 
- page template 
- Side bar template part

**Comment by jaymcp** [comment]
Known issues:
- category archive intro content is missing (e.g. on /latest/news/)
- custom cards with donation actions don't render correctly on /donate/

**Comment by Gentyspun** [comment]
Issues spotted on DEV, these may be unrelated to the epic tickets, and some may be fixable in the editor

- Block spacing issues on most pages. (Must obvious on Homepage and /careers, example: http://bigbite.im/i/hR1TKR)
- Inconsistent image and text sizing on /what-we-do as well as odd spacing (example: http://bigbite.im/i/eElb1j)
- /countries Explore By Region section displays too many regions/sub-regions/countries (example: http://bigbite.im/i/swj6Fs)
- /get-involved similar issues to /what-we-do page
- Counter block displays total number below the counter on /join (example: http://bigbite.im/i/nI7ASB)

**Comment by jaymcp** [comment]
> Block spacing issues on most pages. (Must obvious on Homepage and /careers, example: http://bigbite.im/i/hR1TKR)

likely caused by this line:
https://github.com/amnestywebsite/humanity-theme/blob/main/private/src/styles/pages/article/_base.scss#L92

might be worth scoping that selector to the single.html template

**Comment by jaymcp** [comment]
> Inconsistent image and text sizing on /what-we-do as well as odd spacing (example: http://bigbite.im/i/eElb1j)

likely a result of moving to a pattern for LWI. can perhaps be addressed by either amending the pattern or modifying content.
currently, the pattern is 3 columns with blocks within. perhaps we could do it with rows of three items instead. (e.g. title row, image row, etc)>

**Comment by jaymcp** [comment]
> /countries Explore By Region section displays too many regions/sub-regions/countries (example: http://bigbite.im/i/swj6Fs)

this should now be fixed. i'd forgotten to deploy the updated theme companion plugin. apologies.

**Comment by jaymcp** [comment]
> Counter block displays total number below the counter on /join (example: http://bigbite.im/i/nI7ASB)

caused by a fixed line height here:
https://github.com/amnestywebsite/humanity-theme/blob/develop/wp-content/themes/humanity-theme/theme.json#L379

we should either define line height as a unit-less value, or override it later.

**Comment by BBTomA** [comment]
Front-end issues found:
Footer

- The heading font is wrong, there are no divider lines under the headers and the menu items are missing an underline on hover http://bigbite.im/i/jIUuxk
- The button on hover background colour is set to black rather than the dark grey on the live site http://bigbite.im/i/3C2tlR

Home page
The font colour within the black boxes is set to black which is causing the text not to show http://bigbite.im/i/SdxzRI

What we do page
- Inconsistency on cards http://bigbite.im/i/wpmfBg

Get involved page
- Inconsistency on cards http://bigbite.im/i/OQWKgk
- Further inconsistency on cards http://bigbite.im/i/Rhls9e

Donate page
- The heading font size is a lot smaller than the live site http://bigbite.im/i/WzIyZw
- The cards are not taking up the full width of the columns and the images are not taking up the full width of the cards. Also, the cards heights are inconsistent http://bigbite.im/i/zmsDap

Single news page
- Hero image not filling the width of the section http://bigbite.im/i/ES5U9q
- A repeated issue with black font text showing within black boxes within the related content section http://bigbite.im/i/F0NJb5

Single resource page
- Spacing needed below language selector and download button http://bigbite.im/i/gopuPW
- The sidebar content doesn't match the live site http://bigbite.im/i/gi7Q5q

**Comment by jaymcp** [comment]
> The heading font size is a lot smaller than the live site http://bigbite.im/i/WzIyZw

It seems there's an issue with fluid typography; looking into it.

**Comment by jaymcp** [comment]
spotted an issue with remote attachments (e.g. when viewing ES document on EN site). i'm working on a solution, but it may take me a while to fix it completely.

**Comment by jaymcp** [comment]
> spotted an issue with remote attachments (e.g. when viewing ES document on EN site). i'm working on a solution, but it may take me a while to fix it completely.

this is fixed


> > The heading font size is a lot smaller than the live site http://bigbite.im/i/WzIyZw
> 
> It seems there's an issue with fluid typography; looking into it.

this is also fixed

**Comment by jaymcp** [comment]
last outstanding issues that i'm aware of all relate to the new patterns intended to replace the custom card block. reviewing these now

**Comment by Gentyspun** [comment]
Issues found on https://isaidotorgstg.wpengine.com/en/

- [ ]  Broken hero on /careers http://bigbite.im/i/BfoNVk
- [ ] "Explore By Region" broken on /countries http://bigbite.im/i/E1k4s5 (Was addressed previously so not sure if fix just isn't on staging yet?)
- [ ] CSS output instead of Hero image on the following page: /about-us, /get-involved/join & /get-involved/online-courses http://bigbite.im/i/1y0ogj (I believe you're already aware of these @jaymcp)

**Comment by jaymcp** [comment]
Whilst investigating custom card oddities, I noticed that we hadn't correctly migrated the colour variables in the branding plugin. I've got a PR in to address that. In the interim, some colours may look incorrect on DEV/STG.
