### ISSUE TITLE
Epic - LRC Bug Scrub

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#417]
let's see how many of the LRC bugs we can close! :-) 

### Sprints allocated 
Number of sprints: one

## Goals    
- Reduce bugs count for LRC issues 

- [x] https://github.com/amnestywebsite/amnesty-wp-theme/issues/2974 
https://github.com/amnestywebsite/humanity-theme/pull/426
- [x] https://github.com/amnestywebsite/amnesty-wp-theme/issues/2973
https://github.com/amnestywebsite/humanity-theme/pull/427
- [x] https://github.com/amnestywebsite/amnesty-wp-theme/issues/2938
https://github.com/amnestywebsite/humanity-theme/pull/428
- [x] https://github.com/amnestywebsite/amnesty-wp-theme/issues/2451
https://github.com/amnestywebsite/humanity-theme/pull/429
- [ ] https://github.com/amnestywebsite/amnesty-wp-theme/issues/2945
- [ ] https://github.com/amnestywebsite/amnesty-wp-theme/issues/1373 
- [ ] https://github.com/amnestywebsite/humanity-theme/issues/3
- [x] https://github.com/amnestywebsite/humanity-theme/issues/5
https://github.com/amnestywebsite/humanity-theme/pull/440
- [ ] https://github.com/amnestywebsite/humanity-theme/issues/13
- [ ] https://github.com/amnestywebsite/humanity-theme/issues/352
- [x] https://github.com/amnestywebsite/humanity-theme/issues/327
- [x] https://github.com/amnestywebsite/humanity-theme/issues/325
- [x] https://github.com/amnestywebsite/humanity-theme/issues/7
- [ ] https://github.com/amnestywebsite/internal/issues/125

**Comment by BBTomA** [comment]
@jaymcp closed, feel free to re-open
